#!/usr/bin/env bash
set -euxo pipefail

if [[ -v "GITHUB_SHA" ]]; then
    GIT_ID=${GITHUB_SHA:0:7}
else
    GIT_ID=$(git rev-parse --short=7 HEAD)
fi

if [[ -v "BRANCH_NAME" ]]; then
    GIT_BRANCH=${BRANCH_NAME}
elif [[ -v "GITHUB_HEAD_REF" ]]; then
    GIT_BRANCH=${GITHUB_HEAD_REF}
else
    GIT_BRANCH=$(git symbolic-ref --short HEAD)
fi

ORG=mrc-ide
IMAGE_NAME=daedalus-web-app-db
TAG_SHA="${ORG}/${IMAGE_NAME}:${GIT_ID}"
TAG_BRANCH="${ORG}/${IMAGE_NAME}:${GIT_BRANCH}"
