#!/usr/bin/env bash
set -euxo pipefail
HERE=$(dirname $0)
. $HERE/common

docker tag "$APP_TAG_SHA" "$APP_TAG_BRANCH"
docker push "$APP_TAG_BRANCH"

docker tag "$DB_TAG_SHA" "$DB_TAG_BRANCH"
docker push "$DB_TAG_BRANCH"
