#!/usr/bin/env bash
set -euxo pipefail
HERE=$(dirname $0)
. $HERE/common

# NB SHA image must be built before running this script
docker run --rm -d \
 --name "$APP_IMAGE_NAME" \
 --network=daedalus \
 -p 3000:3000 \
 --env-file env.docker \
 "$APP_TAG_SHA"