#!/usr/bin/env bash
set -euxo pipefail
HERE=$(dirname $0)
. $HERE/common
# run web app image, assuming dependencies are already running
docker run --rm -d \
 --network bridge \
 --name "$APP_IMAGE_NAME" \
 -p 3000:3000 \
 "$APP_TAG_SHA"

# env vars

# TODO: WAIT?

# Migrate the db
docker exec "$APP_IMAGE_NAME" prisma migrate deploy
