<template>
  <CContainer>
    <h1>About</h1>
    <div class="toc">
      <ul>
        <li>
          <a href="#dashboard">The DAEDALUS Explore dashboard</a>
          <ul>
            <li><a href="#hypothetical-diseases">Hypothetical diseases</a></li>
            <li><a href="#policy-responses">Policy responses</a></li>
            <li><a href="#global-vaccine-investment">Global vaccine investment</a></li>
            <li><a href="#change-in-public-behaviour">Change in public behaviour</a></li>
            <li><a href="#hospital-surge-capacity">Hospital surge capacity</a></li>
          </ul>
        </li>
        <li>
          <a href="#results">Results</a>
          <ul>
            <li><a href="#estimates-of-losses">Estimates of losses</a></li>
            <li><a href="#time-series">Time series</a></li>
          </ul>
        </li>
        <li>
          <a href="#intended-use">Intended use</a>
        </li>
        <li>
          <a href="#contact-us">Contact us</a>
        </li>
        <li>
          <a href="#contribution-acknowledgements">Contribution acknowledgements</a>
        </li>
        <li>
          <a href="#funding-acknowledgements">Funding acknowledgements</a>
        </li>
        <li>
          <a href="#disclaimer-and-licensing">Disclaimer and licensing</a>
        </li>
        <template v-if="appStore.versions">
          <li>
            <a href="#version">Version</a>
          </li>
        </template>
        <li>
          <a href="#references">References</a>
        </li>
      </ul>
    </div>
    <h2 id="dashboard">
      The DAEDALUS Explore dashboard
    </h2>
    <p>
      DAEDALUS Explore is an interactive dashboard tool that allows users to project the health, education and economic
      impacts of epidemic scenarios and their mitigation measures. DAEDALUS Explore allows users to simulate what would
      happen in specific countries if one of 7 hypothetical pandemics of varying severity were to
      occur. The 7 diseases
      are hypothetical but informed by the characteristics of pathogens that have caused pandemics in the past. Daedalus
      Explore supports projections for {{ numberOfCountries }} countries, and pulls in data on demography, social mixing
      patterns, and economic sector productivity and workforces from publicly available sources.
    </p>
    <p>
      Projections in DAEDALUS Explore are generated by the integrated economic-epidemiological
      <a href="https://github.com/jameel-institute/daedalus" target="_blank">Daedalus model</a>, allowing
      users to explore the model with a simplified interface and a few top-level parameter options. The Daedalus model
      is based on Doohan et al (2025)<sup>1</sup> and Haw et al (2022)<sup>2</sup>. For full details on the underlying
      Daedalus model visit the
      <a href="https://jameel-institute.github.io/daedalus/" target="_blank">Daedalus model website</a>.
      Please use the Daedalus R package for advanced use cases that are not yet supported by the dashboard.
    </p>
    <h3 id="hypothetical-diseases">
      Hypothetical diseases
    </h3>
    <p>
      Users choose among 7 diseases, to set model parameters for transmissibility, delays and
      severity based on known characteristics of the historical pathogens (see <span class="table-ref">Table 1</span>).
      We assume there is no prior immunity to the disease amongst the countries’ populations.
    </p>
    <table>
      <caption>Table 1:  Characteristics of diseases (modelled on historic pathogens)</caption>
      <thead>
        <tr>
          <th>Disease</th>
          <th>R0 (transmissibility)</th>
          <th>Infection fatality ratio*</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>SARS 2004</td>
          <td>1.8</td>
          <td>3.3% to 7.6%</td>
        </tr>
        <tr>
          <td>Covid-19 Wild-type</td>
          <td>2.9 </td>
          <td>0.26% to 1.4%</td>
        </tr>
        <tr>
          <td>Covid-19 Omicron</td>
          <td>5.9</td>
          <td>0.11% to 0.62%</td>
        </tr>
        <tr>
          <td>Covid-19 Delta</td>
          <td>5.1</td>
          <td>0.47% to 2.5%</td>
        </tr>
        <tr>
          <td>Influenza 2009 (Swine flu)</td>
          <td>1.6</td>
          <td>0.036% to 0.19%</td>
        </tr>
        <tr>
          <td>Influenza 1957</td>
          <td>1.8</td>
          <td>0.069% to 0.39%</td>
        </tr>
        <tr>
          <td>Influenza 1918 (Spanish flu) </td>
          <td>2.5</td>
          <td>0.81% to 1.4%</td>
        </tr>
      </tbody>
      <tfoot>
        <tr>
          <td />
          <td />
          <td>*varies with country demographics</td>
        </tr>
      </tfoot>
    </table>

    <h3 id="policy-responses">
      Policy responses
    </h3>
    <p>
      The user then chooses a policy response amongst four options: No closures, school closures, business closures,
      and elimination (see <span class="table-ref">Table 2</span>). These policy responses simulate non-pharmaceutical economic
      restrictions that governments can mandate once the epidemic reaches pre-defined thresholds, as detailed below.
    </p>
    <table>
      <caption>Table 2: Response policies </caption>
      <thead>
        <tr>
          <th>Response</th>
          <th>In-person teaching in primary and secondary schools </th>
          <th>In-person work and trading for businesses </th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>No closures</td>
          <td>yes</td>
          <td>yes</td>
        </tr>
        <tr>
          <td>School closures</td>
          <td>closure</td>
          <td>some restrictions</td>
        </tr>
        <tr>
          <td>Business closures</td>
          <td>no</td>
          <td>restrictions</td>
        </tr>
        <tr>
          <td>Elimination</td>
          <td>closure</td>
          <td>severe restrictions</td>
        </tr>
      </tbody>
    </table>
    <p>
      Under ‘Elimination’, restrictions are implemented when total hospitalisations (hospital occupancy) breach a
      country’s hospital surge capacity or 30 days after the start of the epidemic, whichever is sooner. We model
      economic restrictions as the reduction in workplace contacts due to the partial closure of economic sectors,
      which affects both transmissions and economic output. Economic restrictions are lifted again once virus
      transmission is suppressed, i.e., the effective reproduction number is below 1. Under school and business
      closures, the same thresholds for restrictions imposition and lifting apply, but only education or non-essential
      economic activity, respectively, are targeted for closures. In school closure scenarios, we assume that the lost
      present value of future earnings due to lost education is reduced due to remote education.
    </p>
    <h3 id="global-vaccine-investment">
      Global vaccine investment
    </h3>
    <p>
      Users can explore the impact of pandemic preparedness on estimated losses, specifically global investments into
      vaccines and vaccine acceptance that are funded by the international community in advance of a pandemic’s arrival.
      A higher level of investment into vaccines allows vaccination to begin earlier, be delivered at a faster rate,
      and to be accepted by a higher proportion of the population. This reduces infections and the need for costly
      closures. There are four levels of investments, ranging from none to high (see <span class="table-ref">Table 3</span>).
    </p>
    <table>
      <caption>Table 3: Global vaccination investments assumptions</caption>
      <thead>
        <tr>
          <th>Global vaccine investment</th>
          <th>Start to vaccinations <br>(after outbreak start)</th>
          <th>Vaccine administration <br>(% population per day)</th>
          <th>Vaccine coverage <br>(% of population)</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>None</td>
          <td>365 days</td>
          <td>0.14%</td>
          <td>40%</td>
        </tr>
        <tr>
          <td>Low</td>
          <td>300 days</td>
          <td>0.29%</td>
          <td>50%</td>
        </tr>
        <tr>
          <td>Medium</td>
          <td>200 days</td>
          <td>0.43%</td>
          <td>60%</td>
        </tr>
        <tr>
          <td>High</td>
          <td>100 days</td>
          <td>0.5%</td>
          <td>80%</td>
        </tr>
      </tbody>
    </table>
    <h3 id="change-in-public-behaviour">
      Change in public behaviour
    </h3>
    <p>
      It is likely that many individuals change their behaviour and adopt precautions as cases increase and they
      perceive a high risk of infection. The user can allow for such effects and specify behaviour change ranging
      from ‘None’ which assumes no protective behaviour to ‘High’ which assumes the population perceives a high risk of
      infection, resulting in high adoption of behaviour that protects against infection. Note that behaviour change
      reduces transmissions but has not direct impact on economic output.
    </p>
    <h3 id="hospital-surge-capacity">
      Hospital surge capacity
    </h3>
    <p>
      The number of hospital beds that are available nationally for the treatment of epidemic patients is prepopulated
      with the actual value from the chosen country. Note that available beds are lower than total beds, which allows
      for the treatment of patients with other urgent conditions. Users can adjust bed capacity up or down within
      reasonable limits.
    </p>
    <h2 id="results">
      Results
    </h2>
    <h3 id="estimates-of-losses">
      Estimates of losses
    </h3>
    <p>
      The dashboard provides estimates of losses after 600 days in the chosen country. Estimated losses are:
    </p>
    <ul>
      <li>Gross Domestic Product (GDP)</li>
      <li>Education</li>
      <li>Life years</li>
    </ul>
    <p>
      Losses in GDP are the short-term losses in economic output due to business closures, which occur unless the
      ‘No closure’ response is chosen. Sickness and deaths amongst workers also result in economic losses. The
      magnitude of losses is based on economic data collected during the COVID-19 pandemic for countries that followed
      one of the three closure strategies. Lost education results in reduced life-time income for affected student.
      We use existing estimates of income reductions and the days of interrupted in-person schooling to estimate lost
      education. To measure deaths in monetary terms, we use the value-of-a-statistical-life (VSL) approach, which
      considers remaining life expectancy at death and GDP of the country to value the loss of life years
      (see <a target="_blank" href="https://jameel-institute.github.io/daedalus/articles/info_life_value.html">Value of
        life-years lost</a> for further details). Losses are provided in both % of pre-pandemic GDP and in US
      dollars. We also output life-years lost and number of deaths in natural units.
    </p>
    <h3 id="time-series">
      Time series
    </h3>
    <p>
      Time series display prevalence, hospital demand or occupancy, cumulative deaths and numbers vaccinated. Toggles
      allow the user to switch the four outcomes to numbers ‘New per day’, i.e. to infection incidence, hospitalizations,
      deaths and numbers vaccinated per day. Hospital surge capacity is indicated by the dashed red line. The blue block
      ‘Pandemic response’ shows the time period over which closures are implemented. User can download all figures and
      the underlying data in various formats and see the R code snippet for running the model with the current parameter set.
    </p>
    <p>
      DAEDALUS Explore allows users to directly compare scenarios against each other, by choosing parameters of specific
      interest. Scenarios can be compared across countries, diseases, response strategies, levels of global vaccine
      investment, change in public behaviour or hospital surge capacity. Results are displayed in stacked bars and
      tables, in total losses or as difference from the baseline.  For fine-grained control over model parameters and
      functionality, R users can run the model directly through the
      <a target="_blank" href="https://jameel-institute.github.io/daedalus/">Daedalus R package</a>.
    </p>
    <h2 id="intended-use">
      Intended use
    </h2>
    <p>
      The DAEDALUS Explore dashboard tool and the Daedalus model are projection and decision-support tools and not
      forecasting tools. The Daedalus model projects outcomes for diseases similar to pathogens that have caused
      historical pandemics. DAEDALUS Explore is not re-creating historical disease outbreaks, and it is not fitted to
      historical epidemic data. Instead, by changing the dashboard’s parameters, DAEDALUS Explore illustrates the
      projected value of differing pandemic preparedness and response activities, and in doing so, endeavours to
      support effective future pandemic planning, preparedness and response.
      The <a target="_blank" href="https://jameel-institute.github.io/daedalus/">Daedalus R package</a> offers many more
      options for customising pathogen, country, and response parameters, allowing for modelling real-time policy
      responses and their projected outcomes.
    </p>
    <h2 id="contact-us">
      Contact us
    </h2>
    <p>
      If you have any queries regarding DAEDALUS Explore, please contact:
      <a href="mailto:daedalus.explore@imperial.ac.uk" class="email">daedalus.explore@imperial.ac.uk</a>
    </p>
    <h2 id="contribution-acknowledgements">
      Contribution Acknowledgements
    </h2>
    <p>
      The DAEDALUS Explore dashboard and the underlying Daedalus model were
      created by ‘The Jameel Institute – Kenneth C Griffin Initiative for the
      Economics of Pandemic Preparedness’ (EPPI), led by Prof Katharina Hauck. It is a partnership between the
      Jameel Institute at Imperial, the Imperial Business School, the World Health Organization and Singapore’s
      Programme For Research In Epidemic Preparedness And Response (PREPARE), National Centre for Infectious Diseases
      (NCID) and Umeå University in Sweden. For more information, visit the website of the
      <a target="_blank" href="https://new.express.adobe.com/webpage/TXLBkz1sN9FI5/">EPPI Initiative</a>.
    </p>
    <p>
      A large team of authors have contributed to the development of DAEDALUS Explore, and the underlying code, since spring 2020.
    </p>
    <h3>Software team</h3>
    <p>
      David Mears<sup>a,b</sup>, Pratik Gupte<sup>a,b</sup>, Emma Russell<sup>a</sup>, Anmol Thapar<sup>a</sup>,
      Mantra Kusumgar<sup>a</sup>, Rich FitzJohn<sup>a</sup>
    </p>
    <h3>Modelling team</h3>
    <p>
      Patrick Doohan<sup>b</sup>*, Rob Johnson<sup>b</sup>*,
      Pratik Gupte<sup>a,b</sup>, David Haw<sup>b,c</sup>,
      Christian Morgenstern<sup>b</sup>, Haokun Peng<sup>g</sup>,
      Pablo Perez Guzman<sup>b</sup>, Kanchan Parchani<sup>b</sup>,
      Guillaume Morel<sup>b,h</sup>, Anh Pham<sup>b,c</sup>,
      Paula Christen<sup>b</sup>, Matteo Pianella<sup>b</sup>,
      Wei Hao Kwok<sup>e</sup>, Jeremy Chan<sup>e</sup>,
      Kelvin Bryan Tan<sup>e</sup>, Peter C Smith<sup>f</sup>, Marisa Miraldo<sup>g</sup>,
      Giovanni Forchini<sup>b,h</sup>, Katharina Hauck<sup>b</sup>
    </p>
    <p>
      * contributed equally
    </p>
    <h3>Project management and communiciations team</h3>
    <p>
      Ellie Farrow<sup>b</sup>, Sara Williams<sup>b</sup>
    </p>
    <h3>Affiliations</h3>
    <ol type="a">
      <li>Reside-IC, MRC Centre for Global Infectious Disease Analysis &amp; Department of Infectious Disease Epidemiology, Imperial, London, United Kingdom</li>
      <li>MRC Centre for Global Infectious Disease Analysis, WHO Collaborating Centre for Infectious Disease Modelling, Jameel Institute, Imperial, London, United Kingdom </li>
      <li>Mathematical Sciences &amp; Infection, Veterinary and Ecological Sciences, University of Liverpool, United Kingdom</li>
      <li>Department of Economics, Stockholm University, Sweden</li>
      <li>PREPARE, National Centre for Infectious Diseases, Singapore</li>
      <li>Centre for Health Economics, University of York, United Kingdom</li>
      <li>Imperial Business School, Imperial, London, United Kingdom</li>
      <li>Umeå School of Business, Economics and Statistics, Umeå Universitet, Umeå, Sweden</li>
    </ol>
    <h2 id="funding-acknowledgements">
      Funding Acknowledgements
    </h2>
    <p>
      The EPPI Initiative gratefully acknowledges research funding from
      Community Jameel and Kenneth C Griffin which enabled the development of
      the DAEDALUS model and DAEDALUS Explore dashboard.
    </p>
    <div class="d-flex flex-wrap justify-content-start align-items-center mb-3 gap-3">
      <img class="p-2" title="Jameel community logo" style="width: 200px" src="~/assets/img/jameel-community-logo.svg" alt="Jameel community logo">
      <img class="p-2" title="Kenneth C Griffin logo" style="width: 200px" src="~/assets/img/GriffinCatalyst_Logo_FullColor.png" alt="Kenneth C Griffin logo">
    </div>
    <h2 id="disclaimer-and-licensing">
      Disclaimer and Licensing
    </h2>
    <h3>Model code license</h3>
    <p>
      The Daedalus model code is provided “as is”, without warranty of any kind,
      express or implied, including but not limited to the warranties of
      merchantability, fitness for a particular purpose and noninfringement.
    </p>
    <p>
      In no event shall the authors or copyright holders be liable for any
      claim, damages or other liability, whether in an action of contract, tort
      or otherwise, arising from, out of or in connection with the software or
      the use or other dealings in the software.
    </p>
    <h3>Icon attributions</h3>
    <p>
      <strong>rotate-device.svg</strong><br>
      Icon by
      <a href="https://github.com/Esri/calcite-ui-icons?ref=svgrepo.com" target="_blank">Esri</a>
      in MIT License via
      <a href="https://www.svgrepo.com/" target="_blank">SVG Repo</a>
    </p>

    <p>
      <strong>carbonSEEarth.svg</strong><br>
      Icon by
      <a href="https://github.com/carbon-design-system/carbon?ref=svgrepo.com" target="_blank">Carbon Design</a>
      in Apache License via
      <a href="https://www.svgrepo.com/" target="_blank">SVG Repo</a>
    </p>

    <p>
      <strong>vectopusVaccine.svg</strong><br>
      Vectors and icon by
      <a href="https://github.com/Vectopus/Atlas-icons-font?ref=svgrepo.com" target="_blank">Vectopus</a>
      in MIT License via
      <a href="https://www.svgrepo.com/" target="_blank">SVG Repo</a>
    </p>

    <p>
      <strong>pictogrammersMaterialBacteria.svg</strong><br>
      Icon by
      <a href="https://github.com/carbon-design-system/carbon?ref=svgrepo.com" target="_blank">Carbon Design</a>
      in Apache License via
      <a href="https://www.svgrepo.com/" target="_blank">SVG Repo</a>
    </p>

    <p>
      <strong>axes-white.png</strong>, <strong>axes-black.png</strong><br>
      Icon by
      <a href="https://www.flaticon.com/free-icon/arrows_10436878" target="_blank">LAFS</a>
      in Flaticon License via
      <a href="https://www.flaticon.com/" target="_blank">Flaticon</a>
    </p>

    <p>
      <strong>info.png</strong>
      Icon by
      <a href="https://www.flaticon.com/free-icons/info" target="_blank">Digby Garrett</a>
      in Flaticon License via
      <a href="https://www.flaticon.com/" target="_blank">Flaticon</a>
    </p>

    <p>
      <strong>social-distance-2-meters-mdi.svg</strong>
      Icon by
      <a href="https://pictogrammers.com/contributor/mririgoyen/" target="_blank">Michael Irigoyen</a>
      in Apache 2.0 License via
      <a href="https://pictogrammers.com/" target="_blank">Pictogrammers</a>
    </p>

    <h3>World map disclaimer and attribution</h3>
    <p>
      The country borders shown on the world map in DAEDALUS Explore are reflective of boundaries as
      employed by the World Health Organization (WHO), including both national borders and disputed
      borders: <a target="_blank" href="https://gis-who.hub.arcgis.com/pages/detailedboundary">https://gis-who.hub.arcgis.com/pages/detailedboundary</a>.
      The code underlying the WHO-aligned world map can be accessed <a target="_blank" href="https://github.com/whocov/whomapper">here</a>.
    </p>
    <p>
      The country borders depicted on the world map do not reflect any expression of opinions by the DAEDALUS Explore
      creators. The world map may be intermittently updated in line with code rewrites, however the timing of such
      updates will be at the discretion of the DAEDALUS Explore creators.
    </p>
    <template v-if="appStore.versions">
      <h2 id="version">
        Version
      </h2>
      <ul>
        <li>Model version: {{ appStore.versions.daedalusModel }}</li>
        <li>R API version: {{ appStore.versions.daedalusApi }}</li>
        <li>Web app version: {{ appStore.versions.daedalusWebApp }}</li>
      </ul>
    </template>
    <h2 id="references">
      References
    </h2>
    <ol>
      <li>
        Doohan, Patrick, Rob Johnson, Alessandra Løchen, Christian Morgenstern, David Haw, Alice Sabino,
        Edith Patouillard, Giovanni Forchini, and Katharina Hauck.
        <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5711172" target="_blank">
          Mitigating Future Respiratory Pandemics in Low-, Middle- and High-Income Countries: A Modelling Study of
          Health, Economic and Educational Losses.
        </a>. Available at <em>SSRN</em>, 2025.
      </li>
      <li>
        Haw, David J., Giovanni Forchini, Patrick Doohan, Paula Christen, Matteo Pianella, Robert Johnson, Sumali Bajaj,
        Alexandra B. Hogan, Peter Winskill, Marisa Miraldo, Peter J. White, Azra C. Ghani, Neil M. Ferguson,
        Peter C. Smith, and Katharina Hauck. 2022.
        <a href="https://www.nature.com/articles/s43588-022-00233-0" target="_blank">
          Optimizing Social and Economic Activity While Containing SARS-CoV-2 Transmission Using DAEDALUS.
        </a>
        <em>Nature Computational Science</em> 2 (4): 223–33.
      </li>
    </ol>
    <div class="d-flex flex-wrap justify-content-center align-items-center mb-5 gap-3">
      <img class="p-2" style="width: 200px" title="Imperial Logo" src="~/assets/img/imperial_logo.svg" alt="Imperial Logo">
      <img class="p-2" title="Prepare logo" style="width: 200px" src="~/assets/img/prepare-logo.png" alt="Prepare logo">
      <img class="p-2" title="Jameel logo" style="width: 250px" src="~/assets/img/jameel-logo1.png" alt="Jameel logo">
    </div>
  </CContainer>
</template>

<script setup lang="ts">
const appStore = useAppStore();
const numberOfCountries = appStore.parametersMetadataById.country?.options?.length;
</script>

<style scoped>
.toc ul{
  list-style-type: none;
  font-size: large;
}

h2, h3 {
  scroll-margin-top: 4.5rem;
}

thead {
  border-bottom-width: 2px;
}

tbody tr {
  border-bottom-width: 1px;
}

th, td {
  padding-right: 2rem;
}

caption {
  font-weight: bold;
  padding-bottom: 2rem;
}

span.table-ref {
  font-weight: bold;
  color: var(--cui-secondary-color)
}
</style>
