<template>
  <CContainer>
    <h1>About</h1>
    <h2>The DAEDALUS Explore dashboard</h2>
    <p>
      DAEDALUS Explore is an interactive dashboard tool that allows users to
      simulate the health, education and economic impacts of hypothetical future
      pandemic scenarios for {{ numberOfPandemics }} pandemics of varying severity in {{ numberOfCountries }}
      countries. The {{ numberOfPandemics }} pandemics are informed by the characteristics of
      pathogens that have caused historic pandemics.
    </p>
    <p>The dashboard provides estimates of:</p>
    <ul>
      <li v-for="estimate in appStore.metadata?.results.time_series_groups" :key="estimate.id">
        {{ estimate.label }}
      </li>
      <li>Economic losses</li>
    </ul>
    <p>
      DAEDALUS Explore allows users to choose a country, a pandemic, and a
      response amongst four options (no closures, school closures, business
      closures, and elimination). Response is the mitigation that policy makers
      can choose once the pandemic strikes. DAEDALUS Explore allows users to
      explore the inherent trade-off between different response strategies. For
      example, business closures may result in higher economic costs, but lower
      deaths compared to a response that does not mandate closures.
    </p>
    <p>
      The losses associated with pandemics can be influenced by investments into
      global vaccine R&D and manufacturing, and into hospital capacity. Users can
      explore the impact of such investments on health, education and economic
      pandemic impacts by comparing the outcomes of scenarios with different
      investments. The impacts of all pandemic scenarios for the countries are
      projected in terms of GDP loss (absolute, and in % of pre-pandemic GDP),
      the long-term income loss caused by the interruption of education in schools,
      and in terms of lost life years, valued in monetary terms.
    </p>

    <h2>The DAEDALUS model</h2>
    <p>
      DAEDALUS Explore is generated by the integrated economic-epidemiological
      model DAEDALUS and uses publicly accessible data sources. For full details
      on the underlying DAEDALUS model visit
      <a href="https://github.com/jameel-institute/daedalus" target="_blank">GitHub</a>
      and read Haw et al (2022).<sup>1</sup>
    </p>
    <h2>Intended use</h2>
    <p>
      The DAEDALUS Explore dashboard tool employs historical disease and policy
      response data and is not updated in response to data generated from
      real-time disease outbreaks. The dashboard is therefore not intended to be
      used as a tool to predict the effects of real epidemic and pandemic
      events, nor is it fitted to health/economic outcome data from previous
      pandemics.
    </p>
    <p>
      Instead, by changing the dashboard’s pandemic characteristics, DAEDALUS
      Explore illustrates the hypothetical societal value of differing pandemic
      preparedness and response activities, and in doing so, endeavours to
      supports effective future pandemic planning, preparedness and response.
    </p>
    <h2>Contact us</h2>
    <p>
      If you have any queries regarding DAEDALUS Explore, please contact:
      <a href="mailto:daedalus.explore@imperial.ac.uk" class="email">daedalus.explore@imperial.ac.uk</a>
    </p>

    <h2>Contribution Acknowledgements</h2>
    <p>
      The DAEDALUS Explore dashboard and the underlying DAEDALUS model were
      created by ‘The Jameel Institute – Kenneth C Griffin Initiative for the
      Economics of Pandemic Preparedness’ (EPPI), a partnership between the
      Jameel Institute at Imperial, the Imperial College Business School, the
      World Health Organization and Singapore’s Programme For Research In
      Epidemic Preparedness And Response (PREPARE), National Centre for
      Infectious Diseases (NCID) and Umeå University in Sweden. For more
      information, visit the website of the <a href="https://new.express.adobe.com/webpage/TXLBkz1sN9FI5/" target="_blank">EPPI Initiative</a>.
    </p>
    <p>
      A large team of authors have contributed to the development of DAEDALUS Explore, and the underlying code, since spring 2020.
    </p>
    <h3>Software team</h3>
    <p>
      David Mears<sup>a,b</sup>, Pratik Gupte<sup>a,b</sup>, Emma Russell<sup>a</sup>, Anmol Thapar<sup>a</sup>,
      Mantra Kusumgar<sup>a</sup>, Rich FitzJohn<sup>a</sup>
    </p>
    <h3>Modelling team</h3>
    <p>
      Patrick Doohan<sup>b</sup>*, Rob Johnson<sup>b</sup>*, David Haw<sup>b,c</sup>, Kanchan Parchani<sup>b</sup>,
      Christian Morgenstern<sup>b</sup>, Matteo Pianella<sup>d</sup>, Wei Hao Kwok<sup>e</sup>, Jeremy Chan<sup>e</sup>,
      Paula Christen<sup>b</sup>, Kelvin Bryan Tan<sup>e</sup>, Peter C Smith<sup>f</sup>, Giovanni Forchini<sup>b,g</sup>,
      Katharina Hauck<sup>b</sup>
    </p>
    <p>
      * contributed equally
    </p>
    <h3>Affiliations</h3>
    <ol type="a">
      <li>Reside-IC, MRC Centre for Global Infectious Disease Analysis &amp; Department of Infectious Disease Epidemiology, Imperial, London, United Kingdom</li>
      <li>MRC Centre for Global Infectious Disease Analysis, Jameel Institute, Imperial, London, United Kingdom</li>
      <li>Mathematical Sciences &amp; Infection, Veterinary and Ecological Sciences, University of Liverpool, United Kingdom</li>
      <li>Department of Economics, Stockholm University, Sweden</li>
      <li>PREPARE, National Centre for Infectious Diseases, Singapore</li>
      <li>Centre for Health Economics, University of York, United Kingdom</li>
      <li>Umeå School of Business, Economics and Statistics, Umeå Universitet, Umeå, Sweden</li>
    </ol>
    <h2>Funding Acknowledgements</h2>
    <p>
      The EPPI Initiative gratefully acknowledges research funding from
      Community Jameel and Kenneth C Griffin which enabled the development of
      the DAEDALUS model and DAEDALUS Explore dashboard.
    </p>
    <div class="d-flex flex-wrap justify-content-start align-items-center mb-3 gap-3">
      <img class="p-2" title="Jameel community logo" style="width: 200px" src="~/assets/img/jameel-community-logo.svg" alt="Jameel community logo">
      <img class="p-2" title="Kenneth C Griffin logo" style="width: 200px" src="~/assets/img/GriffinCatalyst_Logo_FullColor.png" alt="Kenneth C Griffin logo">
    </div>
    <h2>Disclaimer and Licensing</h2>
    <h3>Model code license</h3>
    <p>
      The DAEDALUS model code is provided “as is”, without warranty of any kind,
      express or implied, including but not limited to the warranties of
      merchantability, fitness for a particular purpose and noninfringement.
    </p>
    <p>
      In no event shall the authors or copyright holders be liable for any
      claim, damages or other liability, whether in an action of contract, tort
      or otherwise, arising from, out of or in connection with the software or
      the use or other dealings in the software.
    </p>
    <h3>Icon attributions</h3>
    <p>
      <strong>rotate-device.svg</strong><br>
      Icon by
      <a href="https://github.com/Esri/calcite-ui-icons?ref=svgrepo.com" target="_blank">Esri</a>
      in MIT License via
      <a href="https://www.svgrepo.com/" target="_blank">SVG Repo</a>
    </p>

    <p>
      <strong>carbonSEEarth.svg</strong><br>
      Icon by
      <a href="https://github.com/carbon-design-system/carbon?ref=svgrepo.com" target="_blank">Carbon Design</a>
      in Apache License via
      <a href="https://www.svgrepo.com/" target="_blank">SVG Repo</a>
    </p>

    <p>
      <strong>vectopusVaccine.svg</strong><br>
      Vectors and icon by
      <a href="https://github.com/Vectopus/Atlas-icons-font?ref=svgrepo.com" target="_blank">Vectopus</a>
      in MIT License via
      <a href="https://www.svgrepo.com/" target="_blank">SVG Repo</a>
    </p>

    <p>
      <strong>pictogrammersMaterialBacteria.svg</strong><br>
      Icon by
      <a href="https://github.com/carbon-design-system/carbon?ref=svgrepo.com" target="_blank">Carbon Design</a>
      in Apache License via
      <a href="https://www.svgrepo.com/" target="_blank">SVG Repo</a>
    </p>

    <p>
      <strong>axes-white.png</strong>, <strong>axes-black.png</strong><br>
      Icon by
      <a href="https://www.flaticon.com/free-icon/arrows_10436878" target="_blank">LAFS</a>
      in Flaticon License via
      <a href="https://www.flaticon.com/" target="_blank">Flaticon</a>
    </p>

    <p>
      <strong>info.png</strong>
      Icon by
      <a href="https://www.flaticon.com/free-icons/info" target="_blank">Digby Garrett</a>
      in Flaticon License via
      <a href="https://www.flaticon.com/" target="_blank">Flaticon</a>
    </p>

    <h3>World map disclaimer and attribution</h3>
    <p>
      The country borders shown on the world map in DAEDALUS Explore are reflective of boundaries as
      employed by the World Health Organization (WHO), including both national borders and disputed
      borders: <a target="_blank" href="https://gis-who.hub.arcgis.com/pages/detailedboundary">https://gis-who.hub.arcgis.com/pages/detailedboundary</a>.
      The code underlying the WHO-aligned world map can be accessed <a target="_blank" href="https://github.com/whocov/whomapper">here</a>.
    </p>
    <p>
      The country borders depicted on the world map do not reflect any expression of opinions by the DAEDALUS Explore
      creators. The world map may be intermittently updated in line with code rewrites, however the timing of such
      updates will be at the discretion of the DAEDALUS Explore creators.
    </p>
    <template v-if="appStore.versions">
      <h2>Version</h2>
      <ul>
        <li>Model version: {{ appStore.versions.daedalusModel }}</li>
        <li>R API version: {{ appStore.versions.daedalusApi }}</li>
        <li>Web app version: {{ appStore.versions.daedalusWebApp }}</li>
      </ul>
    </template>
    <h2>References</h2>
    <ol>
      <li>
        Haw, David J., Giovanni Forchini, Patrick Doohan, Paula Christen, Matteo Pianella, Robert Johnson, Sumali Bajaj, et al. 2022.
        <a href="https://www.nature.com/articles/s43588-022-00233-0" target="_blank">
          Optimizing Social and Economic Activity While Containing SARS-CoV-2 Transmission Using DAEDALUS.
        </a>
        <em>Nature Computational Science</em> 2 (4): 223–33.
      </li>
    </ol>
    <div class="d-flex flex-wrap justify-content-center align-items-center mb-5 gap-3">
      <img class="p-2" style="width: 200px" title="Imperial Logo" src="~/assets/img/imperial_logo.svg" alt="Imperial Logo">
      <img class="p-2" title="Prepare logo" style="width: 200px" src="~/assets/img/prepare-logo.png" alt="Prepare logo">
      <img class="p-2" title="Jameel logo" style="width: 250px" src="~/assets/img/jameel-logo1.png" alt="Jameel logo">
    </div>
  </CContainer>
</template>

<script setup lang="ts">
const appStore = useAppStore();
const numberOfPandemics = appStore.parametersMetadataById.pathogen?.options?.length;
const numberOfCountries = appStore.parametersMetadataById.country?.options?.length;
</script>
