<template>
  <CContainer>
    <h1>About</h1>
    <h2>The DAEDALUS Explore dashboard</h2>
    <p>
      DAEDALUS Explore is an interactive dashboard tool that allows users to
      simulate the health, education and economic impacts of hypothetical future
      pandemic scenarios for 7 pandemics of varying severity in over 60
      countries. The 7 pandemics are informed by the characteristics of
      pathogens that have caused historic pandemics.
    </p>
    <p>The dashboard provides estimates of:</p>
    <ul>
      <li>Prevalence</li>
      <li>Hospital demand</li>
      <li>Deaths</li>
      <li>Economic losses</li>
    </ul>
    <p>
      DAEDALUS Explore allows users to choose a country, a pandemic, and a
      response amongst four options (no closures, school closures, business
      closures, and elimination). Response is the mitigation that policy makers
      can choose once the pandemic strikes. DAEDALUS Explore allows user to
      explore the inherent trade-off between different response strategies. For
      example, business closures may result in higher economic costs, but lower
      deaths compared to a response that does not mandate closures.
    </p>
    <p>
      DAEDALUS Explore allows users to choose a country, a pandemic, and a
      response amongst four options (no closures, school closures, business
      closures, and elimination). Response is the mitigation that policy makers
      can choose once the pandemic strikes. DAEDALUS Explore allows user to
      explore the inherent trade-off between different response strategies. For
      example, business closures may result in higher economic costs, but lower
      deaths compared to a response that does not mandate closures.
    </p>

    <h3>The DAEDALUS model</h3>
    <p>
      DAEDALUS Explore is generated by the integrated economic-epidemiological
      model DAEDALUS and uses publicly accessible data sources. For full details
      on the underlying DAEDALUS model visit
      <a href="https://github.com/jameel-institute/daedalus" target="_blank">Github</a>
      and read Haw et al (2022).<sup>1</sup>
    </p>
    <h4>Intended use</h4>
    <p>
      The DAEDALUS Explore dashboard tool employs historical disease and policy
      response data and is not updated in response to data generated from
      real-time disease outbreaks. The dashboard is therefore not intended to be
      used as a tool to predict the effects of real epidemic and pandemic
      events, nor is it fitted to health/economic outcome data from previous
      pandemics.
    </p>
    <p>
      Instead, by changing the dashboard’s pandemic characteristics, DAEDALUS
      Explore illustrates the hypothetical societal value of differing pandemic
      preparedness and response activities, and in doing so, endeavours to
      supports effective future pandemic planning, preparedness and response.
    </p>
    <h4>Contact us:</h4>
    <p>
      If you have any queries regarding DAEDALUS Explore, please contact: TODO
    </p>

    <h4>Acknowledgements</h4>
    <p>
      The DAEDALUS Explore dashboard and the underlying DAEDALUS model was
      created by ‘The Jameel Institute – Kenneth C Griffin Initiative for the
      Economics of Pandemic Preparedness’ (EPPI), a partnership between the
      Jameel Institute at Imperial, the Imperial College Business School, the
      World Health Organization and Singapore’s Programme For Research In
      Epidemic Preparedness And Response (PREPARE), National Centre for
      Infectious Diseases (NCID) and Umeå University in Sweden. For more
      information, visit the website of the EPPI Initiative.
    </p>
    <p>
      The EPPI Initiative gratefully acknowledges research funding from
      Community Jameel and Kenneth C Griffin which enabled the development of
      the DAEDALUS model and DAEDALUS Explore dashboard.
    </p>
    <h4>Disclaimer and Licensing</h4>
    <h5>Model code license</h5>
    <p>
      The DAEDALUS model code is provided “as is”, without warranty of any kind,
      express or implied, including but not limited to the warranties of
      merchantability, fitness for a particular purpose and noninfringement.
    </p>
    <p>
      In no event shall the authors or copyright holders be liable for any
      claim, damages or other liability, whether in an action of contract, tort
      or otherwise, arising from, out of or in connection with the software or
      the use or other dealings in the software.
    </p>
    <h5>Dashboard Icon licenses</h5>
    <p>
      <strong>rotate-device.svg</strong><br>
      Icons by
      <a
        href="https://github.com/Esri/calcite-ui-icons?ref=svgrepo.com"
        target="_blank"
      >Esri</a>
      in MIT License via
      <a href="https://www.svgrepo.com/" target="_blank">SVG Repo</a>
    </p>

    <p>
      <strong>carbonSEEarth.svg</strong><br>
      Icons by
      <a
        href="https://github.com/carbon-design-system/carbon?ref=svgrepo.com"
        target="_blank"
      >Carbon Design</a>
      in Apache License via
      <a href="https://www.svgrepo.com/" target="_blank">SVG Repo</a>
    </p>

    <p>
      <strong>vectopusVaccine.svg</strong><br>
      Vectors and icons by
      <a
        href="https://github.com/Vectopus/Atlas-icons-font?ref=svgrepo.com"
        target="_blank"
      >Vectopus</a>
      in MIT License via
      <a href="https://www.svgrepo.com/" target="_blank">SVG Repo</a>
    </p>

    <p>
      <strong>pictogrammersMaterialBacteria.svg</strong><br>
      Icons by
      <a
        href="https://github.com/carbon-design-system/carbon?ref=svgrepo.com"
        target="_blank"
      >Carbon Design</a>
      in Apache License via
      <a href="https://www.svgrepo.com/" target="_blank">SVG Repo</a>
    </p>
    <h3>References</h3>
    <p>
      Haw, David J., Giovanni Forchini, Patrick Doohan, Paula Christen, Matteo
      Pianella, Robert Johnson, Sumali Bajaj, et al. 2022. “Optimizing Social
      and Economic Activity While Containing SARS-CoV-2 Transmission Using
      DAEDALUS.” Nature Computational Science 2 (4): 223–33.
    </p>
    <div class="d-flex flex-wrap justify-content-between">
      <img
        class="p-2"
        style="width: 200px"
        title="Imperial Logo"
        src="~/assets/img/imperial_logo.svg"
        alt="Imperial Logo"
      >
      <img
        class="p-2"
        title="Prepare logo"
        style="width: 300px"
        src="~/assets/img/prepare-logo.png"
        alt="Prepare logo"
      >
      <img
        class="p-2"
        title="Jameel logo"
        style="width: 200px"
        src="~/assets/img/jameel-logo.jpg"
        alt="Jameel logo"
      >
    </div>
  </CContainer>
</template>

<script setup lang="ts"></script>
