#!/usr/bin/env bash
set -ex

# From now on, if the user presses Ctrl+C we should teardown gracefully
function cleanup() {
  set +ex # allow teardown errors
  docker kill daedalus-web-app-db
  docker kill daedalus-api
  docker kill daedalus-api-worker
  docker kill daedalus-redis
  docker volume remove daedalus-results
  docker network remove daedalus
  set -e
}

cleanup
trap cleanup EXIT

HERE=$(realpath "$(dirname $0)")

"$HERE"/run-dependencies "$@"

# Wait for Ctrl+C
echo "Ready to use. Press Ctrl+C to teardown."
sleep infinity
