#!/usr/bin/env bash
set -ex

HERE=$(realpath "$(dirname $0)")

"$HERE"/run-dependencies "$@"

# From now on, if the user presses Ctrl+C we should teardown gracefully
function cleanup() {
  set +x
  docker kill daedalus-web-app-db
  docker kill daedalus-api
}
trap cleanup EXIT

# Wait for Ctrl+C
echo "Ready to use. Press Ctrl+C to teardown."
sleep infinity
