#!/usr/bin/env bash
set -ex

# From now on, if the user presses Ctrl+C we should teardown gracefully
function cleanup() {
  set +ex # allow teardown errors
  docker rm -f daedalus-web-app-db || true
  docker rm -f daedalus-api || true
  docker rm -f daedalus-api-worker || true
  docker rm -f daedalus-redis || true
  docker volume remove daedalus-results || true
  docker network remove daedalus || true
  set -e
}

cleanup
trap cleanup EXIT

HERE=$(realpath "$(dirname $0)")

"$HERE"/run-dependencies "$@"

# Wait for Ctrl+C
echo "Ready to use. Press Ctrl+C to teardown."
sleep infinity
