#!/usr/bin/env bash

set -eo pipefail

HERE=$(realpath "$(dirname $0)")

usage() {
    echo "Options:"
    echo " -h, --help            Show list of flags"
    echo " --db-build-skip       Skip building the db"
}

DB_BUILD_SKIP=0
handle_options() {
  while [ $# -gt 0 ]; do
    case $1 in
      -h | --help)
        usage
        exit 3
      ;;
      --db-build-skip)
        DB_BUILD_SKIP=1
        ;;
      *)
        echo "Invalid option: $1" >&2
        usage
        exit 1
        ;;
    esac
    shift
  done
}

handle_options "$@"

DB_BUILD_SKIP=${DB_BUILD_SKIP:-0}
"$HERE"/run-database "$DB_BUILD_SKIP"

NETWORK=daedalus
VOLUME=daedalus-results

docker network create $NETWORK
docker network connect daedalus daedalus-web-app-db

docker volume create $VOLUME

# Pull and run the R API image
R_API_IMAGE='mrcide/daedalus.api:main'
docker pull $R_API_IMAGE # There will be a 'latest' tag: https://github.com/jameel-institute/daedalus.api/pull/2#issuecomment-2252491603

QUEUE_ID=daedalus-api-queue-$(uuidgen)

docker run --rm -d \
  -p 127.0.0.1:6379:6379 \
  --name=daedalus-redis \
  --network=$NETWORK \
  redis

docker run --rm -d \
  -p 8001:8001 \
  --name=daedalus-api \
  --network=$NETWORK \
  -v $VOLUME:/daedalus/results \
  --env=DAEDALUS_QUEUE_ID=$QUEUE_ID \
  --env=REDIS_CONTAINER_NAME=daedalus-redis \
  --entrypoint="/usr/local/bin/daedalus.api" \
  $R_API_IMAGE

# Give the api container time to configure the queue
sleep 5

docker run --rm -d \
  --name=daedalus-api-worker \
  --network=$NETWORK \
  -v $VOLUME:/daedalus/results \
  --env=DAEDALUS_QUEUE_ID=$QUEUE_ID \
  --env=REDIS_CONTAINER_NAME=daedalus-redis \
  --entrypoint="/usr/local/bin/daedalus.api.worker" \
  $R_API_IMAGE

